export const SERVICES = [
  { label: "Contract Review", value: "contract_review", basePrice: 200 },
  { label: "Will Preparation", value: "will_preparation", basePrice: 300 },
  { label: "Business Formation", value: "business_formation", basePrice: 500 },
  { label: "Trademark Filing", value: "trademark_filing", basePrice: 400 },
  { label: "Legal Consultation", value: "legal_consultation", basePrice: 150 },
  { label: "Property Law", value: "property_law", basePrice: 350 },
  { label: "Family Law", value: "family_law", basePrice: 300 },
  { label: "Employment Law", value: "employment_law", basePrice: 250 },
  { label: "Personal Injury", value: "personal_injury", basePrice: 400 },
  { label: "Criminal Defense", value: "criminal_defense", basePrice: 500 },
];

export const STATES = [
  { label: "California", value: "CA", tax: 0.0825 },
  { label: "New York", value: "NY", tax: 0.08875 },
  { label: "Texas", value: "TX", tax: 0.0625 },
  { label: "Florida", value: "FL", tax: 0.06 },
  { label: "Illinois", value: "IL", tax: 0.0625 },
  { label: "Pennsylvania", value: "PA", tax: 0.06 },
  { label: "Ohio", value: "OH", tax: 0.055 },
  { label: "Georgia", value: "GA", tax: 0.04 },
  { label: "North Carolina", value: "NC", tax: 0.0475 },
  { label: "Michigan", value: "MI", tax: 0.06 },
  { label: "New Jersey", value: "NJ", tax: 0.0663 },
  { label: "Virginia", value: "VA", tax: 0.053 },
  { label: "Washington", value: "WA", tax: 0.065 },
  { label: "Arizona", value: "AZ", tax: 0.056 },
  { label: "Massachusetts", value: "MA", tax: 0.0625 },
  { label: "Tennessee", value: "TN", tax: 0.07 },
  { label: "Indiana", value: "IN", tax: 0.07 },
  { label: "Missouri", value: "MO", tax: 0.0423 },
  { label: "Maryland", value: "MD", tax: 0.06 },
  { label: "Wisconsin", value: "WI", tax: 0.05 },
  { label: "Colorado", value: "CO", tax: 0.029 },
  { label: "Minnesota", value: "MN", tax: 0.0688 },
  { label: "South Carolina", value: "SC", tax: 0.06 },
  { label: "Alabama", value: "AL", tax: 0.04 },
  { label: "Louisiana", value: "LA", tax: 0.0445 },
  { label: "Kentucky", value: "KY", tax: 0.06 },
  { label: "Oregon", value: "OR", tax: 0.0 },
  { label: "Oklahoma", value: "OK", tax: 0.045 },
  { label: "Connecticut", value: "CT", tax: 0.0635 },
  { label: "Utah", value: "UT", tax: 0.0485 },
  { label: "Iowa", value: "IA", tax: 0.06 },
  { label: "Nevada", value: "NV", tax: 0.0685 },
  { label: "Arkansas", value: "AR", tax: 0.065 },
  { label: "Mississippi", value: "MS", tax: 0.07 },
  { label: "Kansas", value: "KS", tax: 0.065 },
  { label: "New Mexico", value: "NM", tax: 0.05125 },
  { label: "Nebraska", value: "NE", tax: 0.055 },
  { label: "West Virginia", value: "WV", tax: 0.06 },
  { label: "Idaho", value: "ID", tax: 0.06 },
  { label: "Hawaii", value: "HI", tax: 0.04 },
  { label: "New Hampshire", value: "NH", tax: 0.0 },
  { label: "Maine", value: "ME", tax: 0.055 },
  { label: "Montana", value: "MT", tax: 0.0 },
  { label: "Rhode Island", value: "RI", tax: 0.07 },
  { label: "Delaware", value: "DE", tax: 0.0 },
  { label: "South Dakota", value: "SD", tax: 0.045 },
  { label: "North Dakota", value: "ND", tax: 0.05 },
  { label: "Alaska", value: "AK", tax: 0.0 },
  { label: "Vermont", value: "VT", tax: 0.06 },
  { label: "Wyoming", value: "WY", tax: 0.04 },
  { label: "Other", value: "OTHER", tax: 0.05 },
];
